// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBac2KaHnuoplX52FzLTyxt5FJ50cHSEfg',
    appId: '1:71569544479:web:14a1ddcfde8c3cb23e4c2a',
    messagingSenderId: '71569544479',
    projectId: 'flutter-riverpod-project',
    authDomain: 'flutter-riverpod-project.firebaseapp.com',
    storageBucket: 'flutter-riverpod-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3y3Iy5OPVCNyACvt7aNovPp_aYQucq5M',
    appId: '1:71569544479:android:382daef0f9fc0ac03e4c2a',
    messagingSenderId: '71569544479',
    projectId: 'flutter-riverpod-project',
    storageBucket: 'flutter-riverpod-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6reNYw7rTSqi8ZGw2vlb98qsiYJkhn1g',
    appId: '1:71569544479:ios:b8b1e536d7e383d73e4c2a',
    messagingSenderId: '71569544479',
    projectId: 'flutter-riverpod-project',
    storageBucket: 'flutter-riverpod-project.firebasestorage.app',
    iosBundleId: 'com.leezunleong.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6reNYw7rTSqi8ZGw2vlb98qsiYJkhn1g',
    appId: '1:71569544479:ios:6f3369104bbb48543e4c2a',
    messagingSenderId: '71569544479',
    projectId: 'flutter-riverpod-project',
    storageBucket: 'flutter-riverpod-project.firebasestorage.app',
    iosBundleId: 'com.example.riverpodFiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBac2KaHnuoplX52FzLTyxt5FJ50cHSEfg',
    appId: '1:71569544479:web:ac1c3b5a063d73d13e4c2a',
    messagingSenderId: '71569544479',
    projectId: 'flutter-riverpod-project',
    authDomain: 'flutter-riverpod-project.firebaseapp.com',
    storageBucket: 'flutter-riverpod-project.firebasestorage.app',
  );
}
